# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1.0.12
      
      - name: configure-debug
        run:
          xmake config --mode=debug

      - name: build
        run:
          .\build\win32\x86_64\debug\tests

      - name: test
        run: xmake run -vwD tests all

      - name: configure-release
        run:
          .\build\win32\x86_64\release\tests

      - name: build
        run:
          xmake build -rvwD tests

      - name: test
        run: xmake run -vwD tests all  
  
      
